### PR TITLE
add script to start fusilli gtk directly with session or from menu

### PR DESCRIPTION
**Pull request by NiceandGently**
This makes it possible to start fusilli directly with mate-session using a gsettings key.

org.mate.session.required-components windowmanager 'fusilli-gtk'

### CODE REVIEW

**Comment by NiceandGently** [comment]
Only a icon is missing ;)

**Comment by noodlylight** [comment]
Good :)

I think that fusilli-gtk should be renamed to fusilli-mate-gtk and installed only if mate is found. 

Could you change that? 

Thanks a lot for the distcheck fixes.

**Comment by noodlylight** [comment]
The script folder is ok :)

**Comment by NiceandGently** [comment]
> Good :)
< I think that fusilli-gtk should be renamed to fusilli-mate-gtk and installed only if mate is found.
> Could you change that?
> Thanks a lot for the distcheck fixes.

Shure,
if USE_MARCO should do the trick.
.......thinking about to create the tarball with scipt folder if marco dep isn't use.

Btw. do you agree to switch to tar.xv tarballs with 'make dist' ?

**Comment by noodlylight** [comment]
> Shure,
> if USE_MARCO should do the trick.
> .......thinking about to create the tarball with scipt folder if marco dep isn't use.

Sounds reasonable.

> Btw. do you agree to switch to tar.xv tarballs with 'make dist' ?

Yes.

**Comment by NiceandGently** [comment]
Now, installing the script + desktop file depends on maco, but 'make dist' creates all files if marco dep isn't installed.

**Comment by noodlylight** [comment]
Good!

> Now, installing the script + desktop file depends on maco, but 'make dist' creates all files if marco dep isn't installed.

I think this is the expected behavior, the tarball should be able to work on all cases.

Merging!

**Pull request merged**
